

import "./globals.css";



export const metadata = {
  title: "servers",
  description: "Generated by create next app",
};

export default function Layout({ children }) {
  return (
    <>
      <html lang="en">
      <body>
        <Header />
          {children}
        <Footer />
      </body>
      </html>
    </>
  );
}